// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/github.get').default>>>>
    }
    '/api/component-example': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-example.get').default>>>>
    }
    '/api/feedback/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feedback/[id].delete').default>>>>
    }
    '/api/feedback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feedback/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feedback/index.post').default>>>>
    }
    '/api/teams': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams.get').default>>>>
    }
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cors.dev').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/api/_hub/sync-variables': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/sync-variables.post').default>>>>
    }
    '/api/_hub/cache/**:key': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].get').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].options').default>>>>
    }
    '/api/_hub/cache/batch-delete': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/batch-delete.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/batch-delete.post').default>>>>
    }
    '/api/_hub/cache/clear/**:base': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/clear/[...base].delete').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/clear/[...base].options').default>>>>
    }
    '/api/_hub/cache': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/index.get').default>>>>
    }
    '/api/_hub/database/:command': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/[command].post').default>>>>
    }
    '/api/_hub/database/query': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3_10902ef51abf5f43cbc9b00acf93bbf1/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.post').default>>>>
    }
    '/raw/**:slug.md': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/raw/[...slug].md.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@4.1.1_@parcel+watcher@_067f3227bdfdca1921fd2db987667528/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@_efcb5c40c65616daf8273ab342d9fb64/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_mdc/highlight': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+mdc@0.17.4_magicast@0.3.5/node_modules/@nuxtjs/mdc/dist/runtime/highlighter/event-handler').default>>>>
    }
    '/api/component-meta': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-component-meta@0.14.0_magicast@0.3.5/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta.get').default>>>>
    }
    '/api/component-meta.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-component-meta@0.14.0_magicast@0.3.5/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta.json.get').default>>>>
    }
    '/api/component-meta/:component?': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-component-meta@0.14.0_magicast@0.3.5/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta-component.get').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.9_@unhead_7e87ab99fa5ea93cf62397092f3a9ef6/node_modules/nuxt-og-image/dist/runtime/server/routes/font').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-site-config@3.2.5_h3@1_d67ee400ea2af3c2dd6c8e4aa8ffe88f/node_modules/nuxt-site-config/dist/runtime/server/routes/__site-config__/debug').default>>>>
    }
    '/__og-image__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.9_@unhead_7e87ab99fa5ea93cf62397092f3a9ef6/node_modules/nuxt-og-image/dist/runtime/server/routes/debug.json').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.9_@unhead_7e87ab99fa5ea93cf62397092f3a9ef6/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/__og-image__/static/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.9_@unhead_7e87ab99fa5ea93cf62397092f3a9ef6/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/llms.txt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-llms@0.1.3_magicast@0.3.5/node_modules/nuxt-llms/dist/runtime/server/routes/llms.txt.get').default>>>>
    }
    '/llms-full.txt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-llms@0.1.3_magicast@0.3.5/node_modules/nuxt-llms/dist/runtime/server/routes/llms-full.txt.get').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.23_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.23_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/api/component-example/:component?': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-example.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__nuxt_content/:collection/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.7.1_better-_0ff76a6cd2e4d8fb154d877e89c58bf9/node_modules/@nuxt/content/dist/runtime/presets/cloudflare/database-handler').default>>>>
    }
    '/__nuxt_content/:collection/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.7.1_better-_0ff76a6cd2e4d8fb154d877e89c58bf9/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
  }
}
export {}