import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface NuxtcoreCollectionItem extends PageCollectionItemBase {
    titleTemplate?: string;
    links: {
    label: string;
    icon?: string;
    trailingIcon?: string;
    to?: string;
    color?: "primary" | "neutral" | "success" | "warning" | "error" | "info";
    size?: "xs" | "sm" | "md" | "lg" | "xl";
    variant?: "solid" | "outline" | "subtle" | "soft" | "ghost" | "link";
    id?: string;
    target?: "_blank" | "_self";
    }[];
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface NuxtcontentCollectionItem extends PageCollectionItemBase {
    titleTemplate?: string;
    links: {
    label: string;
    icon?: string;
    trailingIcon?: string;
    to?: string;
    color?: "primary" | "neutral" | "success" | "warning" | "error" | "info";
    size?: "xs" | "sm" | "md" | "lg" | "xl";
    variant?: "solid" | "outline" | "subtle" | "soft" | "ghost" | "link";
    id?: string;
    target?: "_blank" | "_self";
    }[];
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface NuxtuiCollectionItem extends PageCollectionItemBase {
    category?: "layout" | "form" | "element" | "navigation" | "data" | "overlay";
    framework?: string;
    module?: string;
    navigation: {
    title?: string;
    };
    links: {
    label: string;
    icon: string;
    avatar?: {
      src: string;
      alt: string;
    };
    to: string;
    target?: string;
    }[];
  }
  

  interface PageCollections {
    nuxtcore: NuxtcoreCollectionItem
    nuxtcontent: NuxtcontentCollectionItem
    nuxtui: NuxtuiCollectionItem
  }

  interface Collections {
    nuxtcore: NuxtcoreCollectionItem
    nuxtcontent: NuxtcontentCollectionItem
    nuxtui: NuxtuiCollectionItem
  }
}
